apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailserver-pvc
  namespace: mailserver
  labels:
    app.kubernetes.io/name: docker-mailserver
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: oci-bv # StorageClass padrão para Block Volume no OKE
  resources:
    requests:
      storage: 50Gi # 1 único volume de 50GB consolidado (limite mínimo OCI)
