apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailserver-pvc
  namespace: mailserver
  labels:
    app.kubernetes.io/name: docker-mailserver
spec:
  accessModes:
    - ReadWriteOnce
  # Sem 'storageClassName' explícito para utilizar a StorageClass padrão (default) configurada no cluster OCI OKE
  resources:
    requests:
      storage: 50Gi # Mínimo de 50GB exigido pela Oracle Cloud
