apiVersion: v1
kind: Secret
metadata:
  name: mailserver-secret
  namespace: mailserver
  labels:
    app.kubernetes.io/name: docker-mailserver
type: Opaque
stringData:
  # Credenciais do provedor de SMTP Relay de saída (ex: Amazon SES ou Brevo)
  # Substitua pelos valores reais fornecidos pelo seu provedor
  RELAY_USER: "seu-usuario-relay@seu-dominio.com.br"
  RELAY_PASS: "sua-senha-ou-api-key-relay"

