apiVersion: v1
kind: Service
metadata:
  name: mailserver-service
  namespace: mailserver
  labels:
    app.kubernetes.io/name: docker-mailserver
  annotations:
    # Anotações para provisionar um Network Load Balancer (NLB - Layer 4) de alta performance na Oracle Cloud (OCI)
    service.beta.kubernetes.io/oci-load-balancer-type: "nlb"
    service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "All"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local # Preserva o IP de origem do cliente para logs e regras de antispam/fail2ban
  selector:
    app.kubernetes.io/name: docker-mailserver
  ports:
    - name: smtp
      port: 25
      targetPort: 25
      protocol: TCP
    - name: smtps
      port: 465
      targetPort: 465
      protocol: TCP
    - name: submission
      port: 587
      targetPort: 587
      protocol: TCP
    - name: imaps
      port: 993
      targetPort: 993
      protocol: TCP
