# Credenciais PostgreSQL do Kong (apenas ambiente de lab local).
apiVersion: v1
kind: Secret
metadata:
  name: lab-postgres
  namespace: lab-kong
  labels:
    app.kubernetes.io/part-of: kong-lab
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  kong-password: kong
