apiVersion: v1
kind: Namespace
metadata:
  name: lab-app
  labels:
    app.kubernetes.io/part-of: kong-lab
---
apiVersion: v1
kind: Namespace
metadata:
  name: lab-kong
  labels:
    app.kubernetes.io/part-of: kong-lab
