# kubernetes/postgres-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
type: Opaque
data:
  POSTGRES_USER: YmFja3N0YWdl # base64 encoded value of "backstage"
  POSTGRES_PASSWORD: aHVudGVyMg== # base64 encoded value of "hunter2"
