# kubernetes/postgres-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
type: Opaque
data:
  POSTGRES_USER: YmFja3N0YWdl # valor em base64 de "backstage"
  POSTGRES_PASSWORD: aHVudGVyMg== # valor em base64 de "hunter2"
