apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: backstage
data:
  app-config.yaml: |
    app:
      baseUrl: http://localhost:8081
    organization:
      name: Spotify
    backend:
      baseUrl: http://localhost:8081 # Adjusted to match Service
      listen:
        port: 7007
      cors:
        origin: http://localhost:8081
