apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-portfolio
  namespace: default
  labels:
    app: sre-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sre-portfolio
  template:
    metadata:
      labels:
        app: sre-portfolio
    spec:
      containers:
      - name: sre-portfolio
        image: aleknots/sre-portfolio:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 100m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sre-portfolio
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: sre-portfolio
  ports:
  - port: 80
    targetPort: 80
