apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-manager-auth-nginx
  namespace: lab-kong
  labels:
    app.kubernetes.io/part-of: kong-lab
    app.kubernetes.io/component: manager-auth
data:
  default.conf: |
    server {
      listen 8080;
      server_name _;

      resolver 10.96.0.10 valid=10s ipv6=off;
      set $admin_api kong-kong-admin.lab-kong.svc.cluster.local;
      set $manager_ui kong-kong-manager.lab-kong.svc.cluster.local;

      auth_basic "Kong Manager";
      auth_basic_user_file /etc/nginx/auth/.htpasswd;

      location = /healthz {
        auth_basic off;
        access_log off;
        return 200;
      }

      location = / {
        return 302 /manager/;
      }

      location = /admin-api {
        proxy_pass http://$admin_api:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location ^~ /admin-api/ {
        proxy_pass http://$admin_api:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location / {
        proxy_pass http://$manager_ui:8002;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
