# Kong Manager HTTP Basic credentials (local lab environment only).
apiVersion: v1
kind: Secret
metadata:
  name: kong-manager-basic-auth
  namespace: lab-kong
  labels:
    app.kubernetes.io/part-of: kong-lab
    app.kubernetes.io/component: manager-auth
type: Opaque
stringData:
  .htpasswd: |
    admin:$apr1$f2c1zjoV$DGF6bSCHvBeDrV7vXyu73/
